[package]
name = "tokio-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
anyhow = "1.0.68"
bytes = "1"
futures = "0.3.26"
async-channel = "1.8.0"
async-stream = "0.3.3"
rand = "0.8.5"
